from locust import HttpUser, task, between

class TicketUser(HttpUser):
    wait_time = between(1, 3)

    @task(2)
    def create_ticket(self):
        self.client.post('/tickets', json={
            'title': 'Load test ticket',
            'description': 'Generated by Locust',
            'priority': 'high',
            'status': 'open',
            'language': 'en'
        })

    @task(1)
    def get_tickets(self):
        self.client.get('/tickets')